### PR TITLE
Add Italian language

### PR DESCRIPTION
**Pull request by lucaam**
It adds the Italian language.

It was tested commenting out the Firebase analytics config and adding `"start": "react-scripts --openssl-legacy-provider start",` to let it run.

### CODE REVIEW

**Comment by lucaam** [comment]
Hello @cynicaloptimist, could you please review?

**Comment by cynicaloptimist** [comment]
Thanks for the PR, I'll review and deploy some time next week. Thanks!

**Comment by cynicaloptimist** [comment]
Merged and deployed. Thanks so much @lucaam, happy holidays!

**Comment by lucaam** [comment]
> Merged and deployed. Thanks so much @lucaam, happy holidays!

Cool, happy holidays to you!

**Pull request merged**
