### PR TITLE
Brazilian portuguese translation

### PR DESCRIPTION
**Pull request by digaofs**
Brazilian portuguese translation files - tested locally.

### CODE REVIEW

**Comment by cynicaloptimist** [comment]
Great work, thanks!

**Comment by cynicaloptimist** [comment]
Localizations are now live on the official website at https://longwave.web.app/. Thanks so much for the contribution!

**Comment by digaofs** [comment]
hi @cynicaloptimist ! Apparently pt-BR is not working yet =/

**Comment by cynicaloptimist** [comment]
Thanks for the heads-up. Should be fixed now, in the meantime I'll need to better understand how i18next does locale resolution :-)

**Pull request merged**
