### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by Fabrice-TIERCELIN**
Hi,

This is a French version of the game.

PS: what is a _cat person_ or a _dog person_?

### CODE REVIEW

**Comment by cynicaloptimist** [comment]
Personne qui aiment des chats / des chiens.

How's my french? :-)

--
Evan Bailey <http://www.linkedin.com/in/evangbailey>
Phone: (575) 694-2835

**Comment by Fabrice-TIERCELIN** [comment]
> 
> How's my french? :-)
> […](#)
> -- Evan Bailey <http://www.linkedin.com/in/evangbailey> Phone: (575) 694-2835

Parfait 👍

**Comment by cynicaloptimist** [comment]
Localizations are now live on the official website at https://longwave.web.app/. Thanks so much for the contribution!

**Comment by Fabrice-TIERCELIN** [comment]
It works!

**Pull request merged**
